---
- hosts: all
  connection: local
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3 
  roles:
    - toma_evidencias
  vars_files:
    - roles/toma_evidencias/vars/main.yml
...
